envs:
- ACCESS_TOKEN: test-token
- ADDON_ACCESS_TOKEN: addon-access-token
- ADDON_HOST: http://localhost:5000
- ADDON_SSO_TOKEN: test
- DATABASE_DRIVER: postgres
- DATABASE_URL: postgres://postgres:postgres@postgres:5432/vdtaddon?sslmode=disable
- GO_ENV: development
- BUCKET: bucket
- PROJECT_ID: project-id
- SERVICE_ACCOUNT_KEY_JSON: |-
    {
        "type": "",
        "project_id": "",
        "private_key_id": "",
        "private_key": "",
        "client_email": "",
        "client_id": "",
        "auth_uri": "",
        "token_uri": "",
        "auth_provider_x509_cert_url": "",
        "client_x509_cert_url": ""
    }
- SESSION_SECRET: session-secret
- AMPLITUDE_TOKEN: 123456
- BITRISE_APP_SLUG: app_slug1
- BITRISE_BUILD_SLUG: build_slug1
- APP_APK_PATH: "$HOME/your/path/to/app.apk"
- TEST_APK_PATH: "$HOME/your/path/to/test.apk"
- BITRISEIO_APP_APK_URL: https://example.com/app.apk
- BITRISEIO_TEST_APK_URL: https://example.com/test.apk
- SKIP_AUTH_WITH_BITRISE_API: 'yes'
- SKIP_SESSION_AUTH: 'yes'
- APP_WEBHOOK_SECRET_ENCRYPT_KEY: '123456789012345678901234567890ab'
- CI: 'true'
