{{ if env "DATABASE_DRIVER" | eq "sqlite3" }}

development:
  dialect: "sqlite3"
  database: {{env "GOPATH" }}/src/github.com/bitrise-io/addons-firebase-testlab/tmp/db/addons-firebase-testlab_development.sqlite

{{ else }}

development:
  dialect: postgres
  database: bitrise_ftl_server_development
  user: postgres
  host: db
  pool: 5

test:
  dialect: postgres
  database: bitrise_ftl_server_test
  user: postgres
  host: db
  pool: 5

{{ if env "DATABASE_URL" | eq "" | not }}
production:
  url: {{env "DATABASE_URL"}}
{{ end }}

{{ end }}
